### ISSUE TITLE
Error on victim side

### ISSUE THREAD

**Issue by HSIS007** [AlteredSecurity/365-Stealer#1]
error=invalid_request&error_description=AADSTS90027%3a+We+are+unable+to+issue+tokens+from+this+API+version+on+the+MSA+tenant.+Please+contact+the+application+vendor+as+they+need+to+use+version+2.0+of+the+protocol+to+support+this.

**Comment by Trouble1-Raunak** [comment]
It might be because you didn't properly configured the details of app registration in 365-Stealer configuration.
Check out this video https://www.youtube.com/watch?v=22ku67tElkI&t=233s
