### ISSUE TITLE
redirect

### ISSUE THREAD

**Issue by moush89** [AlteredSecurity/365-Stealer#2]
![4444](https://user-images.githubusercontent.com/59103671/129446552-657706b2-3dd8-4b61-8dd6-a2e1013c976f.PNG)
 when accepting the app permssions gets redirected to here where it fails.

**Comment by TROUBLE-1** [comment]
its because the request is going to Apache server, but the url belongs to 365-Stealer.py. Run your xampp server on another port like 8000. cuz 443 port need to be available for the Stealer. Please watch the walk-through video on YouTube for the setup

**Comment by moush89** [comment]
how can i come in Contact with you do you have telegram?
